const games = {
	"areathriftyone": {
		"title": "AreaThriftyOne",
		"desc": "A turn-based 2d game that illustrates the feeling of packing your stuff before the big move.",
		"url": "https://zodaink.itch.io/areathriftyone",
		"img": "assets/areathriftyone.png",
		"bg_color": "#2C3B4C",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#414A6A",
	},
	"ballin_brawler": {
		"title": "Ballin Brawler",
		"desc": "A fun local multiplayer brawler.",
		"url": "https://zodaink.itch.io/ballin-brawler",
		"img": "assets/ballin_brawler.png",
		"bg_color": "#769642",
		"title_color": "#60DF59",
		"text_color": "#FFFFFF7F",
		"border_color": "#60DF59",
	},
	"beginners_luck": {
		"title": "Beginner's Luck",
		"desc": "A minigolf game where you play as a dice inside another dice.",
		"url": "https://zodaink.itch.io/beginners-luck",
		"img": "assets/beginners_luck.png",
		"bg_color": "#7B7B7B",
		"title_color": "#F5DF71",
		"text_color": "#FFFFFF7F",
		"border_color": "#ABABAB",
	},
	"instarsect": {
		"title": "Instarsect",
		"desc": "A bullet hell where you control a blackhole to collect bullets, and a fly to shoot the enemies.",
		"url": "https://zodaink.itch.io/gmtk2024",
		"img": "assets/instarsect.png",
		"bg_color": "#1D1E29",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#32395F",
	},
	"krabaten": {
		"title": "Krabaten",
		"desc": "A platformer where you collect trash to protect the crab's sand castle.",
		"url": "https://zodaink.itch.io/krabaten",
		"img": "assets/krabaten.png",
		"bg_color": "#1F455E",
		"title_color": "#FA985B",
		"text_color": "#FFFFFF7F",
		"border_color": "#275B67",
	},
	"little_goats_garden": {
		"title": "Little Goats Garden",
		"desc": "A cute farming sim.",
		"url": "https://spicymajsy.itch.io/little-goats-garden",
		"img": "assets/little_goats_garden.png",
		"bg_color": "#4D3535",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#6D5555",
	},
	"morphality": {
		"title": "Morphality",
		"desc": "Kill all the townspeople to win! Some may drop body parts. Attach them to yourself for new attributes and abilities.",
		"url": "https://spicymajsy.itch.io/morphality",
		"img": "assets/morphality.png",
		"bg_color": "#203457",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#4D788B",
	},
	"overcome": {
		"title": "Overcome",
		"desc": "A platformer about overcoming your flaws.",
		"url": "https://zodaink.itch.io/overcome-global-game-jam-2022",
		"img": "assets/overcome.png",
		"bg_color": "#0C0B18",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#29261D",
	},
	"partner_platformer": {
		"title": "Partner Platformer",
		"desc": "A neat platformer prototype.",
		"url": "https://zodaink.itch.io/partner-platformer-dev",
		"img": "assets/partner_platformer.png",
		"bg_color": "#251B26",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#453B46",
	},
	"puzzlethingie": {
		"title": "Puzzlethingie",
		"desc": "A sokoban inspired puzzle game.",
		"url": "https://zodaink.itch.io/puzzlethingie",
		"img": "assets/puzzlethingie.png",
		"bg_color": "#101112",
		"title_color": "#FF9F00",
		"text_color": "#FF9F007F",
		"border_color": "#303132",
	},
	"shackled": {
		"title": "Shackled",
		"desc": "A dungeon crawler.",
		"url": "https://zodaink.itch.io/gmtk2025",
		"img": "assets/shackled.png",
		"bg_color": "#0F1929",
		"title_color": "#F9A144",
		"text_color": "#FFFFFF7F",
		"border_color": "#2F3949",
	},
	"turtle_racing": {
		"title": "Turtle's Bizarre Bathroom",
		"desc": "A racing game where a tiny turtle races through the bathroom. Has a level editor.",
		"url": "https://zodaink.itch.io/feverdream",
		"img": "assets/turtle_racing.png",
		"bg_color": "#436D5A",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#638D7A",
	},
	"wizz_the_wizard": {
		"title": "Wizz The Wizard",
		"desc": "A turn-based game about Wizz, an employee of Bob’s Bar and Grill who fantasizes about being a wizard, as he takes orders and deals with customer complaints in order to earn money to buy his wife a birthday present.",
		"url": "https://zodaink.itch.io/wizzthewizard",
		"img": "assets/wizz_the_wizard.png",
		"bg_color": "#2A2351",
		"title_color": "#FFFFFF",
		"text_color": "#FFFFFF7F",
		"border_color": "#5E2E49",
	},
};

function game(name) {
	let it = games[name];
	if(typeof it === null || typeof it === undefined) { return; }

	let result = "";
	result = result.concat("",
		'<div class="game" style="background-color: ', it.bg_color,
		'; border: 5px solid ', it.border_color, ';">',
		'<h2><a style="color: ', it.title_color, ';" href="', it.url, '">', it.title, '</a></h2>',
		'<p style="color: ', it.text_color, ';">', it.desc, '</p>',
		'<img src="', it.img, '"/>',
		'</div>'
	);

	document.write(result);
}
